name: Inbox
modelClass: AcornAssociated\Messaging\Models\Message
form: $/acornassociated/messaging/models/message/fields.yaml
defaultRedirect: acornassociated/messaging/inbox
create:
    redirect: 'acornassociated/messaging/inbox/update/:id'
    redirectClose: acornassociated/messaging/inbox
update:
    redirect: acornassociated/messaging/inbox
    redirectClose: acornassociated/messaging/inbox
preview: {  }
