plugin:
    name: 'acornassociated.reporting::lang.plugin.name'
    description: 'acornassociated.reporting::lang.plugin.description'
    author: 'Acorn Associated'
    icon: wn-icon-briefcase
    replaces: {  }
permissions:
    reporting:
        tab: acornassociated.reporting::lang.plugin.name
        label: acornassociated.reporting::lang.permissions.reporting
navigation:
    reporting-menu-item:
        label: Reporting
        url: acornassociated/reporting/reports
        icon: icon-briefcase
        permissions:
            - reporting
