plugin:
    name: 'acorn.reporting::lang.plugin.name'
    description: 'acorn.reporting::lang.plugin.description'
    author: 'Acorn'
    icon: wn-icon-briefcase
    replaces: {  }
permissions:
    reporting:
        tab: acorn.reporting::lang.plugin.name
        label: acorn.reporting::lang.permissions.reporting
navigation:
    reporting-menu-item:
        label: Reporting
        url: acorn/reporting/reports
        icon: icon-briefcase
        permissions:
            - reporting
